name: CICD Webhook test

on: 
    push:
        branches: ["main"]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                lfs: true

            - name: Set image meta data
              id: meta
              uses: actions/docker-metadata-action@v5
              with: 
                images: ${{ secrets.REGISTRY_USER }}/webhook_test2
                tags: | 
                  type=sha
                  latest

            - name: Setup docker engine 
              uses: actions/setup-buildx-action@v3

            - name: Login to dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.REGISTRY_USER }}
                password: ${{secrets.REGISTRY_TOKEN }}
            
            - name: Build and push to dockerhub
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags}}
                cache-from: type=gha
                cache-to: type=gha,mode=max



